import { PrismaClient } from "@prisma/client";
const url = (process.env.DATABASE_URL ?? "").replace("schema=dev", "schema=public");
const db = new PrismaClient({ datasources: { db: { url } } });
const q = async (sql: string) => { try { return await db.$queryRawUnsafe<any[]>(sql); } catch (e) { return [{ error: String(e).slice(0, 120) }]; } };
console.log("public.search_fts rows:", JSON.stringify(await q(`SELECT count(*)::int AS n FROM "public".search_fts`)));
console.log("public.SearchDoc rows:", JSON.stringify(await q(`SELECT count(*)::int AS n FROM "public"."SearchDoc"`)));
console.log("kinds in search_fts:", JSON.stringify(await q(`SELECT kind, count(*)::int AS n FROM "public".search_fts GROUP BY kind`)));
console.log("sample:", JSON.stringify(await q(`SELECT rid, kind, left(title, 40) AS title FROM "public".search_fts LIMIT 5`)));
console.log("prod businesses:", JSON.stringify(await q(`SELECT count(*)::int AS n FROM "public"."Business"`)));
console.log("prod articles:", JSON.stringify(await q(`SELECT count(*)::int AS n FROM "public"."Article"`)));
await db.$disconnect();
